### ISSUE TITLE
キリル文字：誤ったベースラインの位置

### ISSUE THREAD

**Issue by JapanYoshi** [XimcoYuzuriha/Xim_Sans#1]
キリル文字のデー「Д д」のベースラインは、「ЦЩЏ цщџ」と同じく、底辺を通ります。
![image](https://user-images.githubusercontent.com/8707990/192915681-d9862080-c447-4f6e-a79c-ef1c2dd8c5dc.png)

**Comment by JapanYoshi** [comment]
合字 Ꙣ ꙣ Ꚁ ꚁ Ꚉ ꚉ Ԫ ԫ Ԭ ԭ でも同じです。

**Comment by XimcoYuzuriha** [comment]
![image](https://user-images.githubusercontent.com/98686328/192938659-587218aa-fbbc-42eb-bee6-4146aa4dadb9.png)
こちら修正しました。ご指摘ありがとうございます。次回バージョン更新時に修正反映分を公開いたします。
