### ISSUE TITLE
ショー文字：bibからzooまでの上下位置が間違っている

### ISSUE THREAD

**Issue by JapanYoshi** [XimcoYuzuriha/Xim_Sans#2]
![image](https://user-images.githubusercontent.com/8707990/192917069-5440a7d6-1bd2-452f-85c3-0dae834781e2.png)
正しい例
![image](https://user-images.githubusercontent.com/8707990/192917311-8d98b6bd-82ec-4616-b89c-f57c134af3c2.png)

**Comment by XimcoYuzuriha** [comment]
![image](https://user-images.githubusercontent.com/98686328/192938912-d57655f9-af0d-40b6-961d-cdd9d82e12f7.png)
こちら修正しました。ご指摘ありがとうございます。次回バージョン更新時に修正反映分を公開いたします。
